CREATE USER IF NOT EXISTS 'spotter'@'%' IDENTIFIED BY 'spotter';
GRANT ALL PRIVILEGES ON *.* TO 'spotter'@'%';
CREATE DATABASE IF NOT EXISTS spotter_product;
CREATE DATABASE IF NOT EXISTS spotter_tests;
