import Config

# OpenTelemetry development configuration
# Use OTLP exporter by default for local collector workflows
config :opentelemetry,
  span_processor: :batch,
  traces_exporter: :otlp

config :opentelemetry_exporter,
  otlp_protocol: :http_protobuf,
  otlp_endpoint: System.get_env("OTEL_EXPORTER_OTLP_ENDPOINT") || "http://localhost:4318"

config :spotter, Spotter.Repo,
  database: "../path/to/your.db",
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

config :ash, policies: [show_policy_breakdowns?: true]

config :spotter, SpotterWeb.Endpoint,
  code_reloader: true,
  check_origin: false,
  http: [ip: {0, 0, 0, 0}, port: 1100],
  adapter: Bandit.PhoenixAdapter,
  server: true,
  secret_key_base:
    "dev-only-secret-not-for-production-use-minimum-64-bytes-long-enough-placeholder",
  live_reload: [
    patterns: [~r"lib/spotter_web/.*(ex|heex)$"]
  ],
  watchers: [
    node: ["build.js", "--watch", cd: Path.expand("../assets", __DIR__)]
  ]

# Per-worktree overrides (gitignored - generated by scripts/setup_worktree.sh)
if File.exists?(Path.expand("dev.local.exs", __DIR__)) do
  import_config("dev.local.exs")
end
