defmodule Spotter.Repo.Migrations.AddConfigSettings do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:config_settings, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :value, :text, null: false
      add :key, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:config_settings, [:key], name: "config_settings_unique_key_index")
  end

  def down do
    drop_if_exists unique_index(:config_settings, [:key],
                     name: "config_settings_unique_key_index"
                   )

    drop table(:config_settings)
  end
end