defmodule Spotter.Repo.Migrations.AddSessionResumeMetadata do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:sessions) do
      add :custom_title, :text
      add :summary, :text
      add :first_prompt, :text
      add :source_created_at, :utc_datetime_usec
      add :source_modified_at, :utc_datetime_usec
    end
  end

  def down do
    alter table(:sessions) do
      remove :source_modified_at
      remove :source_created_at
      remove :first_prompt
      remove :summary
      remove :custom_title
    end
  end
end