defmodule Spotter.Repo.Migrations.AddComputedLaneCaches do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:computed_lane_caches, primary_key: false) do
      add :team_id,
          references(:teams, column: :id, name: "computed_lane_caches_team_id_fkey", type: :uuid),
          null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :computed_at, :utc_datetime_usec, null: false
      add :version, :bigint, null: false
      add :payload, :binary, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:computed_lane_caches, [:team_id],
             name: "computed_lane_caches_unique_team_index"
           )
  end

  def down do
    drop_if_exists unique_index(:computed_lane_caches, [:team_id],
                     name: "computed_lane_caches_unique_team_index"
                   )

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `computed_lane_caches` table without the `computed_lane_caches_team_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:computed_lane_caches)
  end
end