defmodule Spotter.Repo.Migrations.AddSessionDistillationFields do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:sessions) do
      add :distilled_summary, :text
      add :distilled_model_used, :text
      add :distilled_at, :utc_datetime_usec
      add :hook_ended_at, :utc_datetime_usec
      add :distilled_status, :text
    end

    create table(:session_distillations, primary_key: false) do
      add :session_id,
          references(:sessions,
            column: :id,
            name: "session_distillations_session_id_fkey",
            type: :uuid
          ), null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :input_stats, :map
      add :commit_hashes, {:array, :text}, null: false, default: []
      add :error_reason, :text
      add :raw_response_text, :text
      add :summary_text, :text
      add :summary_json, :map
      add :model_used, :text
      add :status, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:session_distillations, [:session_id],
             name: "session_distillations_unique_session_distillation_index"
           )
  end

  def down do
    drop_if_exists unique_index(:session_distillations, [:session_id],
                     name: "session_distillations_unique_session_distillation_index"
                   )

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `session_distillations` table without the `session_distillations_session_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:session_distillations)

    alter table(:sessions) do
      remove :distilled_status
      remove :hook_ended_at
      remove :distilled_at
      remove :distilled_model_used
      remove :distilled_summary
    end
  end
end