defmodule Spotter.Repo.Migrations.AddCommitFilesAndAnnotationFileRefs do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:commit_files, primary_key: false) do
      add :commit_id,
          references(:commits, column: :id, name: "commit_files_commit_id_fkey", type: :uuid),
          null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :change_type, :text, null: false
      add :relative_path, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:commit_files, [:commit_id, :relative_path],
             name: "commit_files_unique_commit_file_index"
           )

    create table(:annotation_file_refs, primary_key: false) do
      add :project_id,
          references(:projects,
            column: :id,
            name: "annotation_file_refs_project_id_fkey",
            type: :uuid
          ), null: false

      add :annotation_id,
          references(:annotations,
            column: :id,
            name: "annotation_file_refs_annotation_id_fkey",
            type: :uuid
          ), null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :line_end, :bigint, null: false
      add :line_start, :bigint, null: false
      add :relative_path, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(
             :annotation_file_refs,
             [:annotation_id, :relative_path, :line_start, :line_end],
             name: "annotation_file_refs_unique_annotation_file_ref_index"
           )
  end

  def down do
    drop_if_exists unique_index(
                     :annotation_file_refs,
                     [:annotation_id, :relative_path, :line_start, :line_end],
                     name: "annotation_file_refs_unique_annotation_file_ref_index"
                   )

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `annotation_file_refs` table without the `annotation_file_refs_annotation_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `annotation_file_refs` table without the `annotation_file_refs_project_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:annotation_file_refs)

    drop_if_exists unique_index(:commit_files, [:commit_id, :relative_path],
                     name: "commit_files_unique_commit_file_index"
                   )

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `commit_files` table without the `commit_files_commit_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:commit_files)
  end
end