defmodule Spotter.Repo.Migrations.AddCoChangeGroupCommitsAndMemberStats do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:co_change_group_member_stats, primary_key: false) do
      add(
        :project_id,
        references(:projects,
          column: :id,
          name: "co_change_group_member_stats_project_id_fkey",
          type: :uuid
        ),
        null: false
      )

      add(:updated_at, :utc_datetime_usec, null: false)
      add(:inserted_at, :utc_datetime_usec, null: false)
      add(:measured_at, :utc_datetime_usec)
      add(:measured_commit_hash, :text)
      add(:loc, :bigint)
      add(:size_bytes, :bigint)
      add(:member_path, :text, null: false)
      add(:group_key, :text, null: false)
      add(:scope, :text, null: false)
      add(:id, :uuid, null: false, primary_key: true)
    end

    create unique_index(
             :co_change_group_member_stats,
             [:project_id, :scope, :group_key, :member_path],
             name: "co_change_group_member_stats_unique_group_member_stat_index"
           )

    create table(:co_change_group_commits, primary_key: false) do
      add(
        :project_id,
        references(:projects,
          column: :id,
          name: "co_change_group_commits_project_id_fkey",
          type: :uuid
        ),
        null: false
      )

      add(:updated_at, :utc_datetime_usec, null: false)
      add(:inserted_at, :utc_datetime_usec, null: false)
      add(:committed_at, :utc_datetime_usec)
      add(:commit_hash, :text, null: false)
      add(:group_key, :text, null: false)
      add(:scope, :text, null: false)
      add(:id, :uuid, null: false, primary_key: true)
    end

    create unique_index(:co_change_group_commits, [:project_id, :scope, :group_key, :commit_hash],
             name: "co_change_group_commits_unique_group_commit_index"
           )

    create index(:co_change_group_commits, [:project_id, :scope, :group_key],
             name: "co_change_group_commits_project_scope_group_index"
           )

    create index(:co_change_group_member_stats, [:project_id, :scope, :group_key],
             name: "co_change_group_member_stats_project_scope_group_index"
           )

    create index(:co_change_group_member_stats, [:project_id, :member_path],
             name: "co_change_group_member_stats_project_member_path_index"
           )
  end

  def down do
    drop_if_exists(
      unique_index(
        :co_change_group_commits,
        [:project_id, :scope, :group_key, :commit_hash],
        name: "co_change_group_commits_unique_group_commit_index"
      )
    )

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `co_change_group_commits` table without the `co_change_group_commits_project_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop(table(:co_change_group_commits))

    drop_if_exists(
      unique_index(
        :co_change_group_member_stats,
        [:project_id, :scope, :group_key, :member_path],
        name: "co_change_group_member_stats_unique_group_member_stat_index"
      )
    )

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `co_change_group_member_stats` table without the `co_change_group_member_stats_project_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop(table(:co_change_group_member_stats))
  end
end
