defmodule Spotter.Repo.Migrations.AddCommitHotspotsAndReviewItems do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:commit_hotspots, primary_key: false) do
      add(
        :commit_id,
        references(:commits, column: :id, name: "commit_hotspots_commit_id_fkey", type: :uuid),
        null: false
      )

      add(
        :project_id,
        references(:projects,
          column: :id,
          name: "commit_hotspots_project_id_fkey",
          type: :uuid
        ),
        null: false
      )

      add(:updated_at, :utc_datetime_usec, null: false)
      add(:inserted_at, :utc_datetime_usec, null: false)
      add(:metadata, :map, null: false, default: %{})
      add(:analyzed_at, :utc_datetime_usec, null: false)
      add(:model_used, :text, null: false)
      add(:rubric, :map, null: false, default: %{})
      add(:overall_score, :float, null: false)
      add(:symbol_name, :text)
      add(:reason, :text, null: false)
      add(:snippet, :text, null: false)
      add(:line_end, :bigint, null: false)
      add(:line_start, :bigint, null: false)
      add(:relative_path, :text, null: false)
      add(:id, :uuid, null: false, primary_key: true)
    end

    create unique_index(
             :commit_hotspots,
             [:commit_id, :relative_path, :line_start, :line_end, :symbol_name],
             name: "commit_hotspots_unique_commit_hotspot_index"
           )

    create table(:review_items, primary_key: false) do
      add(
        :commit_hotspot_id,
        references(:commit_hotspots,
          column: :id,
          name: "review_items_commit_hotspot_id_fkey",
          type: :uuid
        )
      )

      add(
        :commit_id,
        references(:commits, column: :id, name: "review_items_commit_id_fkey", type: :uuid)
      )

      add(
        :project_id,
        references(:projects, column: :id, name: "review_items_project_id_fkey", type: :uuid),
        null: false
      )

      add(:updated_at, :utc_datetime_usec, null: false)
      add(:inserted_at, :utc_datetime_usec, null: false)
      add(:suspended_at, :utc_datetime_usec)
      add(:last_seen_at, :utc_datetime_usec)
      add(:seen_count, :bigint, null: false)
      add(:interval_days, :bigint)
      add(:next_due_on, :date)
      add(:importance, :text, null: false)
      add(:target_kind, :text, null: false)
      add(:id, :uuid, null: false, primary_key: true)
    end

    create unique_index(
             :review_items,
             [:project_id, :target_kind, :commit_id, :commit_hotspot_id],
             name: "review_items_unique_review_item_index"
           )

    create table(:project_ingest_states, primary_key: false) do
      add(
        :project_id,
        references(:projects,
          column: :id,
          name: "project_ingest_states_project_id_fkey",
          type: :uuid
        ),
        null: false
      )

      add(:updated_at, :utc_datetime_usec, null: false)
      add(:inserted_at, :utc_datetime_usec, null: false)
      add(:last_commit_ingest_at, :utc_datetime_usec)
      add(:id, :uuid, null: false, primary_key: true)
    end

    create unique_index(:project_ingest_states, [:project_id],
             name: "project_ingest_states_unique_project_index"
           )
  end

  def down do
    drop_if_exists(
      unique_index(:project_ingest_states, [:project_id],
        name: "project_ingest_states_unique_project_index"
      )
    )

    drop(table(:project_ingest_states))

    drop_if_exists(
      unique_index(
        :review_items,
        [:project_id, :target_kind, :commit_id, :commit_hotspot_id],
        name: "review_items_unique_review_item_index"
      )
    )

    drop(table(:review_items))

    drop_if_exists(
      unique_index(
        :commit_hotspots,
        [:commit_id, :relative_path, :line_start, :line_end, :symbol_name],
        name: "commit_hotspots_unique_commit_hotspot_index"
      )
    )

    drop(table(:commit_hotspots))
  end
end
