defmodule Spotter.Repo.Migrations.AddTeams do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:teams, primary_key: false) do
      add :project_id,
          references(:projects, column: :id, name: "teams_project_id_fkey", type: :uuid),
          null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :name, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:teams, [:project_id, :name], name: "teams_unique_team_per_project_index")
  end

  def down do
    drop_if_exists unique_index(:teams, [:project_id, :name],
                     name: "teams_unique_team_per_project_index"
                   )

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `teams` table without the `teams_project_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:teams)
  end
end