defmodule Spotter.Repo.Migrations.AddProductSpecRuns do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:product_spec_runs, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :metadata, :map, default: %{}
      add :error, :text
      add :finished_at, :utc_datetime_usec
      add :started_at, :utc_datetime_usec
      add :dolt_commit_hash, :text
      add :git_branch, :text
      add :git_cwd, :text
      add :status, :text, null: false
      add :commit_hash, :text, null: false
      add :project_id, :uuid, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:product_spec_runs, [:project_id, :commit_hash],
             name: "product_spec_runs_unique_run_per_commit_index"
           )
  end

  def down do
    drop_if_exists unique_index(:product_spec_runs, [:project_id, :commit_hash],
                     name: "product_spec_runs_unique_run_per_commit_index"
                   )

    drop table(:product_spec_runs)
  end
end