defmodule Spotter.Repo.Migrations.CreateProjectRollupTables do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:project_rolling_summaries, primary_key: false) do
      add :project_id,
          references(:projects,
            column: :id,
            name: "project_rolling_summaries_project_id_fkey",
            type: :uuid
          ), null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :computed_at, :utc_datetime_usec
      add :model_used, :text
      add :summary_text, :text
      add :summary_json, :map
      add :included_bucket_start_dates, {:array, :text}, null: false, default: []
      add :lookback_days, :bigint, null: false
      add :default_branch, :text, null: false
      add :timezone, :text, null: false
      add :bucket_kind, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(
             :project_rolling_summaries,
             [:project_id, :bucket_kind, :timezone, :default_branch, :lookback_days],
             name: "project_rolling_summaries_unique_rolling_index"
           )

    create table(:project_period_summaries, primary_key: false) do
      add :project_id,
          references(:projects,
            column: :id,
            name: "project_period_summaries_project_id_fkey",
            type: :uuid
          ), null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :computed_at, :utc_datetime_usec
      add :model_used, :text
      add :summary_text, :text
      add :summary_json, :map
      add :included_commit_hashes, {:array, :text}, null: false, default: []
      add :included_session_ids, {:array, :text}, null: false, default: []
      add :default_branch, :text, null: false
      add :timezone, :text, null: false
      add :bucket_start_date, :date, null: false
      add :bucket_kind, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(
             :project_period_summaries,
             [:project_id, :bucket_kind, :bucket_start_date, :timezone, :default_branch],
             name: "project_period_summaries_unique_period_index"
           )
  end

  def down do
    drop_if_exists unique_index(
                     :project_period_summaries,
                     [:project_id, :bucket_kind, :bucket_start_date, :timezone, :default_branch],
                     name: "project_period_summaries_unique_period_index"
                   )

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `project_period_summaries` table without the `project_period_summaries_project_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:project_period_summaries)

    drop_if_exists unique_index(
                     :project_rolling_summaries,
                     [:project_id, :bucket_kind, :timezone, :default_branch, :lookback_days],
                     name: "project_rolling_summaries_unique_rolling_index"
                   )

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `project_rolling_summaries` table without the `project_rolling_summaries_project_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:project_rolling_summaries)
  end
end