defmodule Spotter.Repo.Migrations.AddFlashcardUniqueIdentity do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(:flashcards, [:annotation_id],
             name: "flashcards_unique_flashcard_per_annotation_index"
           )
  end

  def down do
    drop_if_exists unique_index(:flashcards, [:annotation_id],
                     name: "flashcards_unique_flashcard_per_annotation_index"
                   )
  end
end