defmodule Spotter.Repo.Migrations.AddRawHookEvents do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:raw_hook_events, primary_key: false) do
      add :inserted_at, :utc_datetime_usec, null: false
      add :captured_at, :utc_datetime_usec, null: false
      add :env, :map, null: false, default: %{}
      add :hook_payload, :map, null: false
      add :tool_use_id, :text
      add :tool_name, :text
      add :hook_event_name, :text, null: false
      add :session_id, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:raw_hook_events, [:session_id, :tool_use_id, :hook_event_name],
             name: "raw_hook_events_unique_event_index"
           )
  end

  def down do
    drop_if_exists unique_index(:raw_hook_events, [:session_id, :tool_use_id, :hook_event_name],
                     name: "raw_hook_events_unique_event_index"
                   )

    drop table(:raw_hook_events)
  end
end