defmodule Spotter.Repo.Migrations.AddTimezoneToProjects do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:projects) do
      add(:timezone, :text, null: false, default: "Etc/UTC")
    end
  end

  def down do
    alter table(:projects) do
      remove(:timezone)
    end
  end
end
