defmodule Spotter.Repo.Migrations.AddCodeHotspots do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:code_hotspots, primary_key: false) do
      add :file_heatmap_id,
          references(:file_heatmaps,
            column: :id,
            name: "code_hotspots_file_heatmap_id_fkey",
            type: :uuid
          )

      add :project_id,
          references(:projects, column: :id, name: "code_hotspots_project_id_fkey", type: :uuid),
          null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :scored_at, :utc_datetime_usec, null: false
      add :model_used, :text, null: false
      add :rubric, :map, null: false, default: %{}
      add :overall_score, :float, null: false
      add :line_end, :bigint, null: false
      add :line_start, :bigint, null: false
      add :snippet, :text, null: false
      add :relative_path, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:code_hotspots, [:project_id, :relative_path, :line_start],
             name: "code_hotspots_unique_project_snippet_index"
           )
  end

  def down do
    drop_if_exists unique_index(:code_hotspots, [:project_id, :relative_path, :line_start],
                     name: "code_hotspots_unique_project_snippet_index"
                   )

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `code_hotspots` table without the `code_hotspots_project_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `code_hotspots` table without the `code_hotspots_file_heatmap_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:code_hotspots)
  end
end