defmodule Spotter.Repo.Migrations.AddFileHeatmap do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:file_heatmaps, primary_key: false) do
      add :project_id,
          references(:projects, column: :id, name: "file_heatmaps_project_id_fkey", type: :uuid),
          null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :heat_score, :float, null: false
      add :last_changed_at, :utc_datetime_usec
      add :change_count_30d, :bigint, null: false
      add :relative_path, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:file_heatmaps, [:project_id, :relative_path],
             name: "file_heatmaps_unique_project_path_index"
           )
  end

  def down do
    drop_if_exists unique_index(:file_heatmaps, [:project_id, :relative_path],
                     name: "file_heatmaps_unique_project_path_index"
                   )

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `file_heatmaps` table without the `file_heatmaps_project_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:file_heatmaps)
  end
end