defmodule Spotter.Repo.Migrations.AddShellCommandEvents do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:shell_command_events, primary_key: false) do
      add(:inserted_at, :utc_datetime_usec, null: false)
      add(:raw_hook_event_id, :text, null: false)
      add(:captured_at, :utc_datetime_usec, null: false)
      add(:finish_status, :text)
      add(:phase, :text, null: false)
      add(:hook_event_name, :text, null: false)
      add(:command_path, :text, null: false)
      add(:command, :text, null: false)
      add(:tool_name, :text)
      add(:tool_use_id, :text, null: false)
      add(:project_id, :uuid, null: false)
      add(:external_session_id, :text, null: false)
      add(:session_id, :uuid, null: false)
      add(:id, :uuid, null: false, primary_key: true)
    end

    create unique_index(:shell_command_events, [:raw_hook_event_id, :command_path, :phase],
             name: "shell_command_events_unique_event_command_index"
           )

    create index(:shell_command_events, [:project_id, :captured_at])
    create index(:shell_command_events, [:session_id, :captured_at])
    create index(:shell_command_events, [:tool_use_id, :captured_at])
    create index(:shell_command_events, [:captured_at])
  end

  def down do
    drop_if_exists(
      unique_index(
        :shell_command_events,
        [:raw_hook_event_id, :command_path, :phase],
        name: "shell_command_events_unique_event_command_index"
      )
    )

    drop(table(:shell_command_events))
  end
end
