defmodule Spotter.Repo.Migrations.AddTranscriptsDomain do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:subagents, primary_key: false) do
      add(
        :session_id,
        references(:sessions, column: :id, name: "subagents_session_id_fkey", type: :uuid),
        null: false
      )

      add(:updated_at, :utc_datetime_usec, null: false)
      add(:inserted_at, :utc_datetime_usec, null: false)
      add(:message_count, :bigint)
      add(:ended_at, :utc_datetime_usec)
      add(:started_at, :utc_datetime_usec)
      add(:slug, :text)
      add(:agent_id, :text, null: false)
      add(:id, :uuid, null: false, primary_key: true)
    end

    create table(:sessions, primary_key: false) do
      add(
        :project_id,
        references(:projects, column: :id, name: "sessions_project_id_fkey", type: :uuid),
        null: false
      )

      add(:updated_at, :utc_datetime_usec, null: false)
      add(:inserted_at, :utc_datetime_usec, null: false)
      add(:message_count, :bigint)
      add(:schema_version, :bigint, null: false)
      add(:ended_at, :utc_datetime_usec)
      add(:started_at, :utc_datetime_usec)
      add(:version, :text)
      add(:git_branch, :text)
      add(:cwd, :text)
      add(:transcript_dir, :text)
      add(:slug, :text)
      add(:session_id, :uuid, null: false)
      add(:id, :uuid, null: false, primary_key: true)
    end

    create unique_index(:subagents, [:session_id, :agent_id],
             name: "subagents_unique_agent_per_session_index"
           )

    create table(:projects, primary_key: false) do
      add(:updated_at, :utc_datetime_usec, null: false)
      add(:inserted_at, :utc_datetime_usec, null: false)
      add(:pattern, :text, null: false)
      add(:name, :text, null: false)
      add(:id, :uuid, null: false, primary_key: true)
    end

    create unique_index(:sessions, [:session_id], name: "sessions_unique_session_id_index")

    create unique_index(:projects, [:name], name: "projects_unique_name_index")

    create table(:messages, primary_key: false) do
      add(
        :session_id,
        references(:sessions, column: :id, name: "messages_session_id_fkey", type: :uuid),
        null: false
      )

      add(:updated_at, :utc_datetime_usec, null: false)
      add(:inserted_at, :utc_datetime_usec, null: false)
      add(:tool_use_id, :text)
      add(:agent_id, :text)
      add(:is_sidechain, :boolean)
      add(:timestamp, :utc_datetime_usec, null: false)
      add(:content, :map)
      add(:role, :text)
      add(:type, :text, null: false)
      add(:message_id, :text)
      add(:parent_uuid, :text)
      add(:uuid, :text, null: false)
      add(:id, :uuid, null: false, primary_key: true)
    end
  end

  def down do
    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `messages` table without the `messages_session_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop(table(:messages))

    drop_if_exists(unique_index(:projects, [:name], name: "projects_unique_name_index"))

    drop_if_exists(
      unique_index(:sessions, [:session_id], name: "sessions_unique_session_id_index")
    )

    drop(table(:projects))

    drop_if_exists(
      unique_index(:subagents, [:session_id, :agent_id],
        name: "subagents_unique_agent_per_session_index"
      )
    )

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `sessions` table without the `sessions_project_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop(table(:sessions))

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `subagents` table without the `subagents_session_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop(table(:subagents))
  end
end
