defmodule Spotter.Repo.Migrations.AddFlashcardsAndReviewItemsFlashcard do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists unique_index(
                     :review_items,
                     [:commit_hotspot_id, :commit_id, :project_id, :target_kind],
                     name: "review_items_unique_review_item_index"
                   )

    create table(:flashcards, primary_key: false) do
      add :annotation_id,
          references(:annotations,
            column: :id,
            name: "flashcards_annotation_id_fkey",
            type: :uuid
          ), null: false

      add :project_id,
          references(:projects, column: :id, name: "flashcards_project_id_fkey", type: :uuid),
          null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :references, :map, null: false, default: %{}
      add :answer, :text, null: false
      add :front_snippet, :text, null: false
      add :question, :text
      add :id, :uuid, null: false, primary_key: true
    end

    alter table(:review_items) do
      add :flashcard_id,
          references(:flashcards,
            column: :id,
            name: "review_items_flashcard_id_fkey",
            type: :uuid
          )
    end

    create unique_index(
             :review_items,
             [:project_id, :target_kind, :commit_id, :commit_hotspot_id, :flashcard_id],
             name: "review_items_unique_review_item_index"
           )
  end

  def down do
    drop_if_exists unique_index(
                     :review_items,
                     [:project_id, :target_kind, :commit_id, :commit_hotspot_id, :flashcard_id],
                     name: "review_items_unique_review_item_index"
                   )

    alter table(:review_items) do
      remove :flashcard_id
    end

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `flashcards` table without the `flashcards_project_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `flashcards` table without the `flashcards_annotation_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:flashcards)

    create unique_index(
             :review_items,
             [:commit_hotspot_id, :commit_id, :project_id, :target_kind],
             name: "review_items_unique_review_item_index"
           )

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `review_items` table without the `review_items_flashcard_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."
  end
end