defmodule Spotter.Repo.Migrations.AddPromptPatternRunsAndPatterns do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:prompt_pattern_runs, primary_key: false) do
      add(
        :project_id,
        references(:projects,
          column: :id,
          name: "prompt_pattern_runs_project_id_fkey",
          type: :uuid
        )
      )

      add(:updated_at, :utc_datetime_usec, null: false)
      add(:inserted_at, :utc_datetime_usec, null: false)
      add(:completed_at, :utc_datetime_usec)
      add(:started_at, :utc_datetime_usec)
      add(:model_used, :text)
      add(:error, :text)
      add(:status, :text, null: false)
      add(:unique_prompts, :bigint, null: false)
      add(:prompts_analyzed, :bigint, null: false)
      add(:prompts_total, :bigint, null: false)
      add(:max_prompt_chars, :bigint, null: false)
      add(:prompt_limit, :bigint, null: false)
      add(:timespan_days, :bigint)
      add(:scope, :text, null: false)
      add(:id, :uuid, null: false, primary_key: true)
    end

    create table(:prompt_patterns, primary_key: false) do
      add(
        :run_id,
        references(:prompt_pattern_runs,
          column: :id,
          name: "prompt_patterns_run_id_fkey",
          type: :uuid
        ),
        null: false
      )

      add(:updated_at, :utc_datetime_usec, null: false)
      add(:inserted_at, :utc_datetime_usec, null: false)
      add(:confidence, :float)
      add(:examples, :map, null: false)
      add(:project_counts, :map, null: false, default: %{})
      add(:count_total, :bigint, null: false)
      add(:label, :text, null: false)
      add(:needle, :text, null: false)
      add(:id, :uuid, null: false, primary_key: true)
    end

    create unique_index(:prompt_patterns, [:run_id, :needle],
             name: "prompt_patterns_unique_run_needle_index"
           )
  end

  def down do
    drop_if_exists(
      unique_index(:prompt_patterns, [:run_id, :needle],
        name: "prompt_patterns_unique_run_needle_index"
      )
    )

    drop(table(:prompt_patterns))
    drop(table(:prompt_pattern_runs))
  end
end
