defmodule Spotter.Repo.Migrations.AddSessionLineStats do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:sessions) do
      add :lines_added, :bigint, null: false
      add :lines_removed, :bigint, null: false
    end
  end

  def down do
    alter table(:sessions) do
      remove :lines_removed
      remove :lines_added
    end
  end
end