defmodule Spotter.Repo.Migrations.AddPurposeToAnnotations do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:annotations) do
      add(:purpose, :text, null: false, default: "review")
    end
  end

  def down do
    alter table(:annotations) do
      remove(:purpose)
    end
  end
end
