defmodule Spotter.Repo.Migrations.AddSessionTeamFields do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:sessions) do
      add :team_name, :text
      add :agent_name, :text
    end
  end

  def down do
    alter table(:sessions) do
      remove :agent_name
      remove :team_name
    end
  end
end