defmodule Spotter.Repo.Migrations.AddInstructionsLoadedEvents do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:instructions_loaded_events, primary_key: false) do
      add(:inserted_at, :utc_datetime_usec, null: false)
      add(:captured_at, :utc_datetime_usec, null: false)
      add(:size_status, :text)
      add(:lines_loaded, :bigint)
      add(:bytes_loaded, :bigint)
      add(:load_reason, :text)
      add(:memory_type, :text)
      add(:file_path, :text, null: false)
      add(:project_id, :uuid)
      add(:session_id, :uuid)
      add(:external_session_id, :text)
      add(:raw_hook_event_id, :text, null: false)
      add(:id, :uuid, null: false, primary_key: true)
    end

    create unique_index(:instructions_loaded_events, [:raw_hook_event_id],
             name: "instructions_loaded_events_unique_raw_event_index"
           )

    create index(:instructions_loaded_events, [:project_id, :captured_at])
    create index(:instructions_loaded_events, [:external_session_id, :captured_at])
    create index(:instructions_loaded_events, [:captured_at])
  end

  def down do
    drop_if_exists(
      unique_index(:instructions_loaded_events, [:raw_hook_event_id],
        name: "instructions_loaded_events_unique_raw_event_index"
      )
    )

    drop(table(:instructions_loaded_events))
  end
end
