defmodule Spotter.Repo.Migrations.RenameHookEndedAtToSessionEndedAt do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    # Only rename if old column exists (fresh DBs already have session_ended_at)
    %{rows: rows} =
      repo().query!("SELECT name FROM pragma_table_info('sessions') WHERE name = 'hook_ended_at'")

    if rows != [] do
      rename(table(:sessions), :hook_ended_at, to: :session_ended_at)
    end
  end

  def down do
    %{rows: rows} =
      repo().query!(
        "SELECT name FROM pragma_table_info('sessions') WHERE name = 'session_ended_at'"
      )

    if rows != [] do
      rename(table(:sessions), :session_ended_at, to: :hook_ended_at)
    end
  end
end
