defmodule Spotter.Repo.Migrations.ReshapeCommitsAndAnnotations do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:commits) do
      add(:hotspots_status, :text, null: false, default: "pending")
      add(:hotspots_analyzed_at, :utc_datetime_usec)
      add(:hotspots_error, :text)
      add(:hotspots_version, :bigint, null: false, default: 1)
      add(:hotspots_metadata, :map, null: false, default: %{})
    end

    alter table(:annotations) do
      add(:relative_path, :text)
      add(:line_start, :bigint)
      add(:line_end, :bigint)
      add(:metadata, :map, null: false, default: %{})

      add(
        :project_id,
        references(:projects, column: :id, name: "annotations_project_id_fkey", type: :uuid)
      )

      add(
        :commit_id,
        references(:commits, column: :id, name: "annotations_commit_id_fkey", type: :uuid)
      )

      add(
        :commit_hotspot_id,
        references(:commit_hotspots,
          column: :id,
          name: "annotations_commit_hotspot_id_fkey",
          type: :uuid
        )
      )
    end
  end

  def down do
    alter table(:annotations) do
      remove(:commit_hotspot_id)
      remove(:commit_id)
      remove(:project_id)
      remove(:metadata)
      remove(:line_end)
      remove(:line_start)
      remove(:relative_path)
    end

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `annotations` table without the `annotations_project_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `annotations` table without the `annotations_commit_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `annotations` table without the `annotations_commit_hotspot_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    alter table(:commits) do
      remove(:hotspots_metadata)
      remove(:hotspots_version)
      remove(:hotspots_error)
      remove(:hotspots_analyzed_at)
      remove(:hotspots_status)
    end
  end
end
