defmodule Spotter.Repo.Migrations.AddRetroSubmissionsAndItems do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:retro_submissions, primary_key: false) do
      add :project_id,
          references(:projects,
            column: :id,
            name: "retro_submissions_project_id_fkey",
            type: :uuid
          ), null: false

      add :session_id,
          references(:sessions,
            column: :id,
            name: "retro_submissions_session_id_fkey",
            type: :uuid
          ), null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :submitted_at, :utc_datetime_usec, null: false
      add :summary, :text
      add :id, :uuid, null: false, primary_key: true
    end

    create table(:retro_items, primary_key: false) do
      add :retro_submission_id,
          references(:retro_submissions,
            column: :id,
            name: "retro_items_retro_submission_id_fkey",
            type: :uuid
          ), null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :rating, :text
      add :explanation, :text, null: false
      add :observation, :text, null: false
      add :category, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end
  end

  def down do
    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `retro_items` table without the `retro_items_retro_submission_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:retro_items)

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `retro_submissions` table without the `retro_submissions_session_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `retro_submissions` table without the `retro_submissions_project_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:retro_submissions)
  end
end