defmodule Spotter.Repo.Migrations.AddDoltCommitHashToCommitTestRuns do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:commit_test_runs) do
      add :dolt_commit_hash, :text
    end
  end

  def down do
    alter table(:commit_test_runs) do
      remove :dolt_commit_hash
    end
  end
end