defmodule Spotter.Repo.Migrations.AddTestCasesAndCommitTestRuns do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:test_cases, primary_key: false) do
      add :source_commit_id,
          references(:commits, column: :id, name: "test_cases_source_commit_id_fkey", type: :uuid)

      add :project_id,
          references(:projects, column: :id, name: "test_cases_project_id_fkey", type: :uuid),
          null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :metadata, :map, null: false, default: %{}
      add :confidence, :float
      add :then, {:array, :text}, null: false, default: []
      add :when, {:array, :text}, null: false, default: []
      add :given, {:array, :text}, null: false, default: []
      add :line_end, :bigint
      add :line_start, :bigint
      add :test_name, :text, null: false
      add :describe_path, {:array, :text}, null: false, default: []
      add :framework, :text, null: false
      add :relative_path, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(
             :test_cases,
             [:project_id, :relative_path, :framework, :describe_path, :test_name],
             name: "test_cases_unique_test_case_index"
           )

    alter table(:commits) do
      add :tests_status, :text, null: false
      add :tests_analyzed_at, :utc_datetime_usec
      add :tests_error, :text
      add :tests_version, :bigint, null: false
      add :tests_metadata, :map, null: false, default: %{}
    end

    create table(:commit_test_runs, primary_key: false) do
      add :commit_id,
          references(:commits, column: :id, name: "commit_test_runs_commit_id_fkey", type: :uuid),
          null: false

      add :project_id,
          references(:projects,
            column: :id,
            name: "commit_test_runs_project_id_fkey",
            type: :uuid
          ), null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :completed_at, :utc_datetime_usec
      add :started_at, :utc_datetime_usec
      add :error, :text
      add :output_stats, :map, null: false, default: %{}
      add :input_stats, :map, null: false, default: %{}
      add :model_used, :text
      add :status, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:commit_test_runs, [:project_id, :commit_id],
             name: "commit_test_runs_unique_commit_test_run_index"
           )
  end

  def down do
    drop_if_exists unique_index(:commit_test_runs, [:project_id, :commit_id],
                     name: "commit_test_runs_unique_commit_test_run_index"
                   )

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `commit_test_runs` table without the `commit_test_runs_project_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `commit_test_runs` table without the `commit_test_runs_commit_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:commit_test_runs)

    alter table(:commits) do
      remove :tests_metadata
      remove :tests_version
      remove :tests_error
      remove :tests_analyzed_at
      remove :tests_status
    end

    drop_if_exists unique_index(
                     :test_cases,
                     [:project_id, :relative_path, :framework, :describe_path, :test_name],
                     name: "test_cases_unique_test_case_index"
                   )

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `test_cases` table without the `test_cases_project_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `test_cases` table without the `test_cases_source_commit_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:test_cases)
  end
end