defmodule Spotter.Repo.Migrations.AddTeamMembers do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:team_members, primary_key: false) do
      add :session_id,
          references(:sessions, column: :id, name: "team_members_session_id_fkey", type: :uuid),
          null: false

      add :team_id,
          references(:teams, column: :id, name: "team_members_team_id_fkey", type: :uuid),
          null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :agent_name, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:team_members, [:team_id, :session_id],
             name: "team_members_unique_member_per_team_index"
           )
  end

  def down do
    drop_if_exists unique_index(:team_members, [:team_id, :session_id],
                     name: "team_members_unique_member_per_team_index"
                   )

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `team_members` table without the `team_members_team_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `team_members` table without the `team_members_session_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:team_members)
  end
end