defmodule Spotter.Repo.Migrations.AddMessageUpsertIdentity do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(:messages, [:session_id, :uuid],
             name: "messages_unique_session_uuid_index"
           )
  end

  def down do
    drop_if_exists unique_index(:messages, [:session_id, :uuid],
                     name: "messages_unique_session_uuid_index"
                   )
  end
end