defmodule Spotter.Repo.Migrations.AddSpecTestLinks do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:spec_test_links, primary_key: false) do
      add :project_id,
          references(:projects,
            column: :id,
            name: "spec_test_links_project_id_fkey",
            type: :uuid
          ), null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :metadata, :map, null: false, default: %{}
      add :source, :text, null: false
      add :confidence, :float, null: false
      add :test_key, :text, null: false
      add :requirement_spec_key, :text, null: false
      add :commit_hash, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(
             :spec_test_links,
             [:project_id, :commit_hash, :requirement_spec_key, :test_key],
             name: "spec_test_links_unique_spec_test_link_index"
           )
  end

  def down do
    drop_if_exists unique_index(
                     :spec_test_links,
                     [:project_id, :commit_hash, :requirement_spec_key, :test_key],
                     name: "spec_test_links_unique_spec_test_link_index"
                   )

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `spec_test_links` table without the `spec_test_links_project_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:spec_test_links)
  end
end