defmodule Spotter.Repo.Migrations.AddPromptPatternMatches do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:prompt_pattern_matches, primary_key: false) do
      add :session_id,
          references(:sessions,
            column: :id,
            name: "prompt_pattern_matches_session_id_fkey",
            type: :uuid
          ), null: false

      add :message_id,
          references(:messages,
            column: :id,
            name: "prompt_pattern_matches_message_id_fkey",
            type: :uuid
          ), null: false

      add :pattern_id,
          references(:prompt_patterns,
            column: :id,
            name: "prompt_pattern_matches_pattern_id_fkey",
            type: :uuid
          ), null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:prompt_pattern_matches, [:pattern_id, :message_id],
             name: "prompt_pattern_matches_unique_pattern_message_index"
           )
  end

  def down do
    drop_if_exists unique_index(:prompt_pattern_matches, [:pattern_id, :message_id],
                     name: "prompt_pattern_matches_unique_pattern_message_index"
                   )

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `prompt_pattern_matches` table without the `prompt_pattern_matches_pattern_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `prompt_pattern_matches` table without the `prompt_pattern_matches_message_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `prompt_pattern_matches` table without the `prompt_pattern_matches_session_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:prompt_pattern_matches)
  end
end